### PR TITLE
Needs Permissions

### PR DESCRIPTION
**Pull request by noelbrownback**
https://github.com/actions/deploy-pages#security-considerations

### CODE REVIEW

**Comment by NathanVaughn** [comment]
I don't *think* this is the problem. By default, an Action has all permissions. I believe this is a configuration in the repo settings under Pages to allow the docs branch to deploy

**Comment by NathanVaughn** [comment]
https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#deployment-branches

**Comment by noelbrownback** [comment]
image

I did that prior to making this PR

**Comment by NathanVaughn** [comment]
I don't think you need any code changes then. Try re-running the Action as-is

**Comment by NathanVaughn** [comment]
NVM, I see

**Comment by noelbrownback** [comment]
image
I did and this is what it showed

**Pull request merged**
